In [1]:
import pandas as pd
import numpy as np

from jupyterthemes import jtplot
jtplot.style('monokai')

def exportCSV (data, filename): #dataframe filename
    data.to_csv (f'{filename}.csv', index=False)

In [2]:
data = pd.read_csv('aggregates.csv') #Записываем датасет в data

In [3]:
data.head()

,client_id,report_date,cnt_zp_1m,cnt_zp_3m,cnt_zp_6m,cnt_zp_12m,downlimit_count,uplimit_count,limit_exchange_count,cur_credit_limit,...,curdel_30plus_bki,curdel_60plus_bank,curdel_60plus_bki,curdel_tech_bank,curdel_tech_bki,bank_1_29_5y_debtor,bank_30_59_5y_debtor,bank_60_89_5y_debtor,bank_90_119_5y_debtor,bank_120plus_5y_debtor
0,4268,2019-11-01 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,8951,2019-11-01 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3485,2019-11-01 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,8008,2019-11-01 00:00:00,2.0,6.0,12.0,24.0,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,1615,2019-11-01 00:00:00,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

### Выводим кол-во пропущенных значений по каждому столбцу data

In [4]:
for col in data.columns:
    pct_missing = np.mean(data[col].isnull())
    print('{} - {}%'.format(col, round(pct_missing*100)))

client_id - 0%
report_date - 0%
cnt_zp_1m - 18%
cnt_zp_3m - 18%
cnt_zp_6m - 18%
cnt_zp_12m - 18%
downlimit_count - 57%
uplimit_count - 57%
limit_exchange_count - 57%
cur_credit_limit - 57%
cur_cr_lim_month - 57%
prev_credit_limit - 57%
max_outstanding_amount_1m - 87%
max_outstanding_amount_3m - 87%
max_outstanding_amount_6m - 86%
max_ovd_amount_1m - 87%
max_ovd_amount_3m - 87%
max_ovd_amount_6m - 86%
avg_outstanding_amount_1m - 87%
avg_outstanding_amount_3m - 87%
avg_outstanding_amount_6m - 86%
avg_ovd_amount_1m - 87%
avg_ovd_amount_3m - 87%
avg_ovd_amount_6m - 86%
max_utilization_1m - 87%
max_utilization_3m - 87%
max_utilization_6m - 86%
avg_utilization_1m - 87%
avg_utilization_3m - 87%
avg_utilization_6m - 86%
avg_debt_3m - 87%
avg_debt_6m - 86%
utilization - 87%
total_num_cards - 3%
cnt_active - 3%
cnt_cur - 3%
first_opened - 3%
last_opened - 3%
last6m_opened - 3%
last6m1y_opened - 3%
num_credit_cards - 3%
num_debit_cards - 3%
num_prem_cards - 3%
extra_card_ind - 3%
actual_credit_card_flg - 87%
cnt_dep_5y - 65%
cnt_dep_closed_5y - 65%
cnt_dep_act - 65%
cnt_dep_6m - 65%
cnt_prolong_max - 65%
amt_min_prlg_max - 73%
cnt_prolong_max_5y - 75%
amt_min_prlg_max_5y - 78%
cnt_foreign_cur_5y - 65%
max_term_50_5y_closed - 89%
max_term_50_5y_open - 92%
max_term_closed - 85%
max_term_open - 75%
cnt_term_g1y_closed - 65%
cnt_term_g1y_open - 65%
min_amt_term_g1y_closed - 96%
min_amt_term_g1y_open - 87%
cnt_early_withdraw_5y - 65%
cnt_account_5y - 65%
max_amt_dep_5y - 75%
max_amt_dep_closed_5y - 88%
max_amt_dep_act - 88%
max_amt_dep_6m - 90%
max_amt_foreign_cur_5y - 98%
sum_dep_now - 75%
sum_acc_now - 88%
avg_sum_cls2op - 86%
avg_sum_nws2op - 89%
max_max_dep_balance - 65%
min_max_dep_balance - 68%
max_max_dep_income - 67%
sum_dep_income_1month - 88%
avg_dep_avg_balance_1month - 76%
max_dep_avg_balance_1month - 65%
sum_dep_expense_1month - 88%
sum_dep_income_3month - 84%
avg_dep_avg_balance_3month - 75%
max_dep_avg_balance_3month - 65%
sum_dep_expense_3month - 84%
sum_dep_income_6month - 80%
sum_dep_expense_6month - 80%
avg_dep_avg_balance_6month - 74%
max_dep_avg_balance_6month - 65%
avg_dep_avg_balance_12month - 72%
max_dep_avg_balance_12month - 65%
gender - 36%
app_rel_status - 36%
app_real_estate_ind - 72%
app_vehicle_ind - 72%
app_education_nm - 36%
app_industry_nm - 36%
app_employment_type_nm - 36%
app_position_type_nm - 36%
app_last_job_experience_from_val - 74%
app_last_job_experience_to_val - 74%
app_total_job_experience_val - 77%
app_addresses_equal - 36%
app_phone_home_flag - 36%
app_client_category - 36%
app_cc_cnt - 36%
app_potreb_cnt - 36%
app_mrtg_cnt - 36%
app_lst_request_m_term - 36%
app_lst_potreb_m_term - 71%
app_fst_request_m_term - 36%
sum_sal_acc_inc_6month_amt_rur - 56%
app_income_from_amt - 83%
app_income_to_amt - 83%
cnt_opened - 43%
mrtg_open - 43%
cl_open - 43%
auto_open - 43%
card_open - 43%
micro_open - 43%
other_open - 43%
cnt_opened_6m - 43%
cnt_opened_1y - 43%
cnt_closed - 43%
mrtg_closed - 43%
cl_closed - 43%
auto_closed - 43%
card_closed - 43%
micro_closed - 43%
other_closed - 43%
cl_closed_gr500k - 43%
cl_closed_gr100k - 43%
cl_closed_gr50k - 43%
cl_closed_ls50k - 43%
length_bank - 43%
length_bank_total - 43%
length_total - 43%
avg_liab_sum_total - 43%
avg_liab_sum_total_open_agr - 43%
avg_liab_sum_total_closed_agr - 43%
max_liab_sum_bank_open - 43%
max_liab_sum_bki_open - 43%
max_liab_sum_bank_closed - 43%
max_liab_sum_bki_closed - 43%
total_liab_sum_bank_open_agr - 43%
total_liab_sum_bki_open_agr - 43%
total_liab_sum_bank_closed_agr - 43%
total_liab_sum_bki_closed_agr - 43%
outstanding - 43%
outstanding_open - 43%
avg_delinquent_debt_total - 43%
curr_arrear_rur - 43%
utilization_avg - 78%
cnt_liability_types - 43%
total_curr_payment - 43%
only_guarantees - 43%
cnt_inquiry_last1w - 66%
cnt_inquiry_last1m - 66%
cnt_inquiry_last3m - 66%
cnt_inquiry_last6m - 66%
cre_date - 66%
total_curr_payment_rkk - 43%
bank_liab_paym - 43%
bki_liab_paym - 43%
bki_loan_lst_close_m_term - 70%
bki_loan_till_lst_close_m_term - 89%
bank_loan_lst_close_m_term - 81%
bank_loan_till_lst_close_m_term - 80%
bank_loan_lst_rate - 75%
bank_loan_fst_rate - 75%
bank_ki_flg - 43%
max_paym_bank - 75%
min_paym_bank - 75%
max_paym_bank_act - 86%
min_paym_bank_act - 86%
bank_count_first_6m_1 - 43%
bank_count_first_6m_30 - 43%
bank_count_first_6m_60 - 43%
bank_count_first_6m_90 - 43%
bank_count_first_12m_1 - 43%
bank_count_first_12m_30 - 43%
bank_count_first_12m_60 - 43%
bank_count_first_12m_90 - 43%
first_payment_default - 43%
second_payment_default - 43%
age - 0%
cnt_adv_repayment - 43%
cnt_adv_repayment_gr_500k - 43%
cnt_adv_repayment_gr_100k - 43%
cnt_adv_repayment_gr_50k - 43%
cnt_adv_repayment_ls_50k - 43%
ratio_adv_repayment - 62%
ratio_adv_repayment_adv_gr_500k - 87%
ratio_adv_repayment_adv_gr_100k - 71%
ratio_adv_repayment_adv_gr_50k - 67%
ratio_adv_repayment_adv_ls_50k - 76%
ratio_cl_closed - 65%
ratio_cl_closed_gr500k - 92%
ratio_cl_closed_gr100k - 74%
ratio_cl_closed_gr50k - 71%
ratio_cl_closed_ls50k - 76%
avg_liab_sum_total_adv_agr - 43%
avg_diff_plan_fact_closed - 62%
total_liab_sum_bank_adv_agr - 43%
total_liab_sum_bki_adv_agr - 43%
cnt_adv25_closed - 43%
total_liab_sum_bank_adv25_agr - 43%
total_liab_sum_bki_adv25_agr - 43%
curdel_0plus_bank - 43%
curdel_0plus_bki - 43%
curdel_30plus_bank - 43%
curdel_30plus_bki - 43%
curdel_60plus_bank - 43%
curdel_60plus_bki - 43%
curdel_tech_bank - 43%
curdel_tech_bki - 43%
bank_1_29_5y_debtor - 43%
bank_30_59_5y_debtor - 43%
bank_60_89_5y_debtor - 43%
bank_90_119_5y_debtor - 43%
bank_120plus_5y_debtor - 43%

### Создаем список нужных столбцов, все остальные отбрасываем

In [5]:
our_col = ['sum_dep_income_1month', 'sum_dep_expense_1month', 'report_date',
'avg_ovd_amount_6m',
'avg_utilization_6m',
'sum_dep_income_6month',
'sum_dep_expense_6month',
'ratio_cl_closed_gr100k',
'app_real_estate_ind',
'app_vehicle_ind',
'cnt_inquiry_last6m',
'ratio_cl_closed',
'sum_sal_acc_inc_6month_amt_rur',
'cnt_opened',
'mrtg_open',
'cl_open',
'auto_open',
'card_open',
'micro_open',
'other_open',
'cnt_opened_6m',
'cnt_opened_1y',
'cnt_closed',
'mrtg_closed',
'cl_closed',
'auto_closed',
'card_closed',
'micro_closed',
'other_closed',
'length_bank',
'length_bank_total',
'length_total',
'outstanding',
'total_curr_payment_rkk',
'bank_ki_flg',
'bank_1_29_5y_debtor',
'bank_30_59_5y_debtor',
'bank_60_89_5y_debtor',
'bank_90_119_5y_debtor',
'bank_120plus_5y_debtor',
'gender',
'app_cc_cnt',
'app_potreb_cnt',
'app_mrtg_cnt',
'app_lst_request_m_term',
'cnt_active',
'last6m_opened',
'last6m1y_opened',
'total_num_cards',
'client_id',
'age']

In [6]:
for col in data.columns:
    if col in our_col:
        pass
    else:
        data = data.drop(columns = col)

In [7]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 177963 entries, 0 to 177962
Data columns (total 51 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   client_id                       177963 non-null  int64
 1   report_date                     177963 non-null  object
 2   avg_ovd_amount_6m               24029 non-null   float64
 3   avg_utilization_6m              24029 non-null   float64
 4   total_num_cards                 173397 non-null  float64
 5   cnt_active                      173397 non-null  float64
 6   last6m_opened                   173397 non-null  float64
 7   last6m1y_opened                 173397 non-null  float64
 8   sum_dep_income_1month           21471 non-null   float64
 9   sum_dep_expense_1month          21471 non-null   float64
 10  sum_dep_income_6month           34829 non-null   float64
 11  sum_dep_expense_6month          34829 non-null   float64
 12  gender                          113352 non-null  float64
 13  app_real_estate_ind             49114 non-null   float64
 14  app_vehicle_ind                 49114 non-null   float64
 15  app_cc_cnt                      113352 non-null  float64
 16  app_potreb_cnt                  113352 non-null  float64
 17  app_mrtg_cnt                    113352 non-null  float64
 18  app_lst_request_m_term          113352 non-null  float64
 19  sum_sal_acc_inc_6month_amt_rur  78961 non-null   float64
 20  cnt_opened                      101575 non-null  float64
 21  mrtg_open                       101575 non-null  float64
 22  cl_open                         101575 non-null  float64
 23  auto_open                       101575 non-null  float64
 24  card_open                       101575 non-null  float64
 25  micro_open                      101575 non-null  float64
 26  other_open                      101575 non-null  float64
 27  cnt_opened_6m                   101575 non-null  float64
 28  cnt_opened_1y                   101575 non-null  float64
 29  cnt_closed                      101575 non-null  float64
 30  mrtg_closed                     101575 non-null  float64
 31  cl_closed                       101575 non-null  float64
 32  auto_closed                     101575 non-null  float64
 33  card_closed                     101575 non-null  float64
 34  micro_closed                    101575 non-null  float64
 35  other_closed                    101575 non-null  float64
 36  length_bank                     101575 non-null  float64
 37  length_bank_total               101575 non-null  float64
 38  length_total                    101575 non-null  float64
 39  outstanding                     101575 non-null  float64
 40  cnt_inquiry_last6m              61268 non-null   float64
 41  total_curr_payment_rkk          101575 non-null  float64
 42  bank_ki_flg                     101575 non-null  float64
 43  age                             177963 non-null  float64
 44  ratio_cl_closed                 63004 non-null   float64
 45  ratio_cl_closed_gr100k          45583 non-null   float64
 46  bank_1_29_5y_debtor             101575 non-null  float64
 47  bank_30_59_5y_debtor            101575 non-null  float64
 48  bank_60_89_5y_debtor            101575 non-null  float64
 49  bank_90_119_5y_debtor           101575 non-null  float64
 50  bank_120plus_5y_debtor          101575 non-null  float64
dtypes: float64(49), int64(1), object(1)
memory usage: 69.2+ MB

In [8]:
data['report_date'] = pd.to_datetime(data['report_date'])

#### Делим исходный датасет на test и train. Доля train - 0.9, test - 0.1 от исходного

In [9]:
msk = np.random.rand(len(data)) < 0.9
train = data[msk]
test = data[~msk]

In [10]:
df1, df2 = [x for _, x in train.groupby(train['report_date'] >= "2020-01-01")]

In [11]:
df1['report_date'].unique()

array(['2019-11-01T00:00:00.000000000', '2019-02-01T00:00:00.000000000',
       '2019-03-01T00:00:00.000000000', '2019-12-01T00:00:00.000000000',
       '2019-10-01T00:00:00.000000000', '2019-09-01T00:00:00.000000000',
       '2019-01-01T00:00:00.000000000', '2019-04-01T00:00:00.000000000',
       '2019-06-01T00:00:00.000000000', '2019-08-01T00:00:00.000000000',
       '2019-05-01T00:00:00.000000000', '2019-07-01T00:00:00.000000000'],
      dtype='datetime64[ns]')

In [12]:
df2['report_date'].unique()

array(['2020-09-01T00:00:00.000000000', '2020-06-01T00:00:00.000000000',
       '2020-07-01T00:00:00.000000000', '2020-04-01T00:00:00.000000000',
       '2020-08-01T00:00:00.000000000', '2020-01-01T00:00:00.000000000',
       '2020-02-01T00:00:00.000000000', '2020-03-01T00:00:00.000000000',
       '2020-05-01T00:00:00.000000000', '2020-10-01T00:00:00.000000000'],
      dtype='datetime64[ns]')

In [13]:
data_2019_1 = pd.DataFrame(df1, columns = ['client_id','report_date', 'avg_ovd_amount_6m','avg_utilization_6m','sum_dep_income_6month',
                                           'sum_dep_expense_6month','sum_sal_acc_inc_6month_amt_rur', 'age', 
                                           'gender','bank_ki_flg','cnt_closed','length_total','outstanding',
                                           'total_curr_payment_rkk','app_real_estate_ind','app_vehicle_ind',
                                           'cnt_inquiry_last6m', 'ratio_cl_closed', 'cnt_opened_6m'])

data_2019_2 = pd.DataFrame(df1, columns = ['client_id','report_date', 'mrtg_open', 'cl_open', 'auto_open', 'card_open', 
                                           'micro_open', 'other_open',  'age', 'gender','bank_ki_flg','cnt_closed',
                                           'length_total','outstanding',
                                           'total_curr_payment_rkk','app_real_estate_ind','app_vehicle_ind',
                                           'cnt_inquiry_last6m', 'ratio_cl_closed', 'cnt_opened_6m'])

data_2019_3 = pd.DataFrame(df1, columns = ['client_id','report_date', 'app_cc_cnt','app_potreb_cnt','app_mrtg_cnt', 'age', 
                                           'gender','bank_ki_flg','cnt_closed','length_total','outstanding',
                                           'total_curr_payment_rkk','app_real_estate_ind','app_vehicle_ind',
                                           'cnt_inquiry_last6m', 'ratio_cl_closed', 'cnt_opened_6m'])

data_2019_4 = pd.DataFrame(df1, columns = ['client_id','report_date', 'bank_1_29_5y_debtor','bank_30_59_5y_debtor',
                                           'bank_60_89_5y_debtor',
                                           'bank_90_119_5y_debtor','bank_120plus_5y_debtor', 'age', 
                                           'gender','bank_ki_flg','cnt_closed','length_total','outstanding',
                                           'total_curr_payment_rkk','app_real_estate_ind','app_vehicle_ind',
                                           'cnt_inquiry_last6m', 'ratio_cl_closed', 'cnt_opened_6m'])

data_2020_1 = pd.DataFrame(df2, columns = ['client_id','report_date', 'avg_ovd_amount_6m','avg_utilization_6m',
                                           'sum_dep_income_6month',
                                           'sum_dep_expense_6month','sum_sal_acc_inc_6month_amt_rur', 'age', 
                                           'gender','bank_ki_flg','cnt_closed','length_total','outstanding',
                                           'total_curr_payment_rkk','app_real_estate_ind','app_vehicle_ind',
                                           'cnt_inquiry_last6m', 'ratio_cl_closed', 'cnt_opened_6m'])

data_2020_2 = pd.DataFrame(df2, columns = ['client_id','report_date', 'mrtg_open', 'cl_open', 'auto_open', 'card_open', 
                                           'micro_open', 'other_open', 'age', 'gender','bank_ki_flg','cnt_closed',
                                           'length_total','outstanding',
                                           'total_curr_payment_rkk','app_real_estate_ind','app_vehicle_ind',
                                           'cnt_inquiry_last6m', 'ratio_cl_closed', 'cnt_opened_6m'])

data_2020_3 = pd.DataFrame(df2, columns = ['client_id','report_date', 'app_cc_cnt','app_potreb_cnt','app_mrtg_cnt', 'age', 
                                           'gender','bank_ki_flg','cnt_closed','length_total','outstanding',
                                           'total_curr_payment_rkk','app_real_estate_ind','app_vehicle_ind',
                                           'cnt_inquiry_last6m', 'ratio_cl_closed', 'cnt_opened_6m'])

data_2020_4 = pd.DataFrame(df2, columns = ['client_id','report_date', 'bank_1_29_5y_debtor','bank_30_59_5y_debtor',
                                           'bank_60_89_5y_debtor','bank_90_119_5y_debtor','bank_120plus_5y_debtor', 'age', 
                                           'gender','bank_ki_flg','cnt_closed','length_total','outstanding',
                                           'total_curr_payment_rkk','app_real_estate_ind','app_vehicle_ind',
                                           'cnt_inquiry_last6m', 'ratio_cl_closed', 'cnt_opened_6m'])

In [14]:
lists_sets = [data_2019_1, data_2019_2, data_2019_3, data_2019_4, 
              data_2020_1, data_2020_2, data_2020_3, data_2020_4]

In [15]:
data_2019_1 = data_2019_1.dropna()
data_2019_2 = data_2019_2.dropna()
data_2019_3 = data_2019_3.dropna()
data_2019_4 = data_2019_4.dropna()
data_2020_1 = data_2020_1.dropna()
data_2020_2 = data_2020_2.dropna()
data_2020_3 = data_2020_3.dropna()
data_2020_4 = data_2020_4.dropna()

### Группировка по полугодиям для каждого из 8 датасетов

In [16]:
data_2019_1_1, data_2019_1_2 = [x for _, x in data_2019_1.groupby(data_2019_1['report_date'] >= "2019-06-30")]
data_2019_2_1, data_2019_2_2 = [x for _, x in data_2019_2.groupby(data_2019_2['report_date'] >= "2019-06-30")]
data_2019_3_1, data_2019_3_2 = [x for _, x in data_2019_3.groupby(data_2019_3['report_date'] >= "2019-06-30")]
data_2019_4_1, data_2019_4_2 = [x for _, x in data_2019_4.groupby(data_2019_4['report_date'] >= "2019-06-30")]

data_2020_1_1, data_2020_1_2 = [x for _, x in data_2020_1.groupby(data_2020_1['report_date'] >= "2020-06-30")]
data_2020_2_1, data_2020_2_2 = [x for _, x in data_2020_2.groupby(data_2020_2['report_date'] >= "2020-06-30")]
data_2020_3_1, data_2020_3_2 = [x for _, x in data_2020_3.groupby(data_2020_3['report_date'] >= "2020-06-30")]
data_2020_4_1, data_2020_4_2 = [x for _, x in data_2020_4.groupby(data_2020_4['report_date'] >= "2020-06-30")]

### Группировка по полю client_id для всех 16 датасетов и среднее по всем остальным полям

In [17]:
data_2019_1_1 = data_2019_1_1.groupby('client_id', as_index=False).mean()
data_2019_1_2 = data_2019_1_2.groupby('client_id', as_index=False).mean()
data_2019_2_1 = data_2019_2_1.groupby('client_id', as_index=False).mean()
data_2019_2_2 = data_2019_2_2.groupby('client_id', as_index=False).mean()
data_2019_3_1 = data_2019_3_1.groupby('client_id', as_index=False).mean()
data_2019_3_2 = data_2019_3_2.groupby('client_id', as_index=False).mean()
data_2019_4_1 = data_2019_4_1.groupby('client_id', as_index=False).mean()
data_2019_4_2 = data_2019_4_2.groupby('client_id', as_index=False).mean()

data_2020_1_1 = data_2020_1_1.groupby('client_id', as_index=False).mean()
data_2020_1_2 = data_2020_1_2.groupby('client_id', as_index=False).mean()
data_2020_2_1 = data_2020_2_1.groupby('client_id', as_index=False).mean()
data_2020_2_2 = data_2020_2_2.groupby('client_id', as_index=False).mean()
data_2020_3_1 = data_2020_3_1.groupby('client_id', as_index=False).mean()
data_2020_3_2 = data_2020_3_2.groupby('client_id', as_index=False).mean()
data_2020_4_1 = data_2020_4_1.groupby('client_id', as_index=False).mean()
data_2020_4_2 = data_2020_4_2.groupby('client_id', as_index=False).mean()

In [18]:
final_sets = [data_2019_1_1, data_2019_1_2, data_2019_2_1, data_2019_2_2, 
              data_2019_3_1, data_2019_3_2, data_2019_4_1, data_2019_4_2,
              data_2020_1_1, data_2020_1_2, data_2020_2_1, data_2020_2_2, 
              data_2020_3_1, data_2020_3_2, data_2020_4_1, data_2020_4_2
             ]

In [19]:
p = 1
arraysDict = {}

final_sets = [
    data_2019_1_1, data_2019_1_2, data_2019_2_1, data_2019_2_2, 
    data_2019_3_1, data_2019_3_2, data_2019_4_1, data_2019_4_2,
    data_2020_1_1, data_2020_1_2, data_2020_2_1, data_2020_2_2, 
    data_2020_3_1, data_2020_3_2, data_2020_4_1, data_2020_4_2
]

titles = [
    'money_2019_1',
    'money_2019_2',
    'others_2019_1',
    'others_2019_2',
    'applications_2019_1',
    'applications_2019_2',
    'delays_2019_1',
    'delays_2019_2',
    'money_2020_1',
    'money_2020_2',
    'others_2020_1',
    'others_2020_2',
    'applications_2020_1',
    'applications_2020_2',
    'delays_2020_1',
    'delays_2020_2'
]

for i in final_sets:
    arraysDict['x_{0}'.format(p)]= i  
    p+=1

In [20]:
p = 0 
for key in arraysDict:
    exportCSV(arraysDict[key], titles[p].strip("'"))
    p+=1

In [21]:
exportCSV(test, 'test')